### ISSUE TITLE
refactor: figure out how to do estimators

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#805]
Currently, using an sklearn pipeline gives a bunch of limitations. We cannot:
* Log to the loggers
* Transform the datasets (feature selection)

Some things would be neat, but can also be done in evaluation:
* Access the attributes of the pipeline elements (e.g. feature importances)

However, being able to just save a scikit-learn pipe is also very nice! So, what do we do? Can we create a pipeline-like element, e.g. a subclass of the scikit-learn estimators, which we can use?

**Comment by HLasse** [comment]
One partial solution is to use the [pipeline](https://imbalanced-learn.org/stable/references/generated/imblearn.pipeline.Pipeline.html) from [imbalanced-learn](https://imbalanced-learn.org/stable/) instead of sklearn's pipeline. As previously discussed, it's a drop-in replacement, but allows for estimators that transform the dataset (adding/removing rows - uncertain about cols). 

For feature selection (dropping columns), it seems there are some fairly simple solutions here: https://stackoverflow.com/questions/68402691/adding-dropping-column-instance-into-a-pipeline

Happy to discuss this more!

**Comment by HLasse** [comment]
Also, making own estimators is fairly straightforward. Here's an example of wrapping an existing one (which could be done to e.g. add a logger to an existing pipeline): https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/607/commits/4be5abc9a1ee7ac67279b51b7f6e32058648484b

**Comment by HLasse** [comment]
Just remembered that I made an estimator for textdescriptives a long time ago - not daunting at all: https://github.com/HLasse/TextDescriptives/blob/main/src/textdescriptives/integrations/sklearn_featurizer.py
